apiVersion: apps/v1
kind: Deployment
metadata:
  name: conduit-pod
  namespace: conduit-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: conduit
  template:
    metadata:
      labels:
        app: conduit
    spec:
      containers:
        # conduit-api container configuration
        - name: conduit-api
          resources:
            limits:
              cpu: "2000m" # Up to 2 full cores
            requests:
              cpu: "1000m" # Use 1 full cores