apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/conduit-pod/
patchesStrategicMerge:
  - ./kind-conduit-patch.yaml
#  - name: openzipkin
#    newName: openzipkin/zipkin
#    newTag: "2.23"
images:
  - name: conduit-api-image
    newName: conduit-api-amd64
    newTag: "1.0"